blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import IndexView,TimelineView,DetailView,CategoryView,TagView,MySearchView,Aboutview,SilianView



urlpatterns = [
    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^timeline/$',TimelineView.as_view(),name='timeline'),
    url(r'^article/(?P<slug>[\w-]+)/$',DetailView.as_view(),name='detail'),
    url(r'^category/(?P<slug>[\w-]+)/$',CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<slug>[\w-]+)/$',TagView.as_view(),name='tag'),
    url(r'^search/$', MySearchView.as_view(), name='search_view'),
    url(r'^about/$',Aboutview,name='about'),
    url(r'^silian\.xml$',SilianView.as_view(content_type='application/xml'),name='silian'),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from blog.feeds import AllArticleRssFeed

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from django.views.generic import TemplateView

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comments/', include('comment.urls', namespace='comment')),  # comment
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^tools/',include('tools.urls',namespace='tools')), # tools
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

tools/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import wordsearch,wordsearch_api

urlpatterns = [
    url(r'^wordsearch/$',wordsearch,name='wordsearch'),
    url(r'^wordserach_api/$',wordsearch_api,name='wordsearch_api'),
]

tools/models.py
from django.db import models

# Create your models here.

tools/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .spider_apis import *


# Create your views here.

def wordsearch(request):
    return render(request,'tools/wordsearch.html',context={})

@login_required
def wordsearch_api(request):
    word = request.GET.get('word')
    tb = TB_WordSearch(word)
    tb_results = tb.get_result()
    tm = TM_WordSearch(word)
    tm_results = tm.get_result()
    jd = JD_WordSearch(word)
    jd_results = jd.get_results()
    return JsonResponse({'tb_results':tb_results,
                         'tm_results':tm_results,
                         'jd_results':jd_results,
                         })

tools/templates/tools/wordsearch.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block head_title %}工具 - 淘宝/天猫关键词搜索{% endblock %}

{% block css-file %}
<style>
#article-tool {
    color:#9B59B6;
}
#article-tool:hover {
    color:#2ecc71;
    text-decoration: none;
}
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 main-box">
            <div class="panel panel-info">
                <div class="panel-heading"><i class="fa fa-book"></i> 工具介绍</div>
                <div class="panel-body">
                    <p>这个工具实现一个简单的搜索结果数据反馈功能，引用的是淘宝和天猫的搜索 API，实际上是一个爬虫。返回的结果就是用户在使用淘宝、天猫搜索功能的时候出现的提示词以及每个词包含的宝贝总数。</p>
                    <p>这个工具只有已经登录本博客的用户才能使用！</p>
                    <p>工具工作原理和代码介绍可以查看文章：
                        <a href="http://www.stopfollow.com/article/taobao-title-word-search-for-choose-words/" id="article-tool">淘宝京东标题关键词搜索，使用爬虫实现精确选词</a>
                    </p>
                    <p>目前已经覆盖电商平台：淘宝、天猫、京东</p>
                    <p>发现搜索数据和实际数据有偏差或者疑问以及任何建议和意见都可以前往上面链接的文章中评论反馈！</p>
                </div>
            </div>
            <div class="input-group">
                <input type="text" class="form-control" id="tb-search" placeholder="输入标题长尾词">
                <span class="input-group-btn">
                    {% if user.is_authenticated %}
                    <button class="btn btn-info" id="tb-go" type="button">搜索</button>
                    {% else %}
                    <button class="btn btn-warning" disabled="disabled" type="button" title="请登录后使用">请登录后搜索</button>
                    {% endif %}
                </span>
            </div><!-- /input-group -->
            <div class="well" style="margin-top:20px;">
                <h2>淘宝搜索结果：</h2>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>相关长尾词</th>
                        <th>宝贝数量</th>
                    </tr>
                    </thead>
                    <tbody id="tb-results"></tbody>
                </table>
                <h2>天猫搜索结果：</h2>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>相关长尾词</th>
                        <th>宝贝数量</th>
                        <th>未知参数1</th>
                        <th>未知参数2</th>
                    </tr>
                    </thead>
                    <tbody id="tm-results"></tbody>
                </table>
                <h2>京东搜索结果：</h2>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>相关长尾词</th>
                        <th>宝贝数量</th>
                    </tr>
                    </thead>
                    <tbody id="jd-results"></tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4 right-box">
            {% include 'blog/tags/base-right.html'%}
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'blog/tags/base-footer.html' %}
{% endblock %}

{% block js-file %}
<script src="{% static 'blog/mystyle/js/tools.js'%}"></script>
<script>
$(document).ready(function(){
    $("#tb-go").click(function(){
        wordsearch_func("{% url 'tools:wordsearch_api' %}")
    });
})

</script>
{% endblock %}