blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import IndexView,TimelineView,DetailView,CategoryView,TagView,MySearchView,Aboutview,SilianView



urlpatterns = [
    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^timeline/$',TimelineView.as_view(),name='timeline'),
    url(r'^article/(?P<slug>[\w-]+)/$',DetailView.as_view(),name='detail'),
    url(r'^category/(?P<slug>[\w-]+)/$',CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<slug>[\w-]+)/$',TagView.as_view(),name='tag'),
    url(r'^search/$', MySearchView.as_view(), name='search_view'),
    url(r'^about/$',Aboutview,name='about'),
    url(r'^silian\.xml$',SilianView.as_view(content_type='application/xml'),name='silian'),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from blog.feeds import AllArticleRssFeed

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from django.views.generic import TemplateView

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comments/', include('comment.urls', namespace='comment')),  # comment
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^tools/',include('tools.urls',namespace='tools')), # tools
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

oauth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import profile_view, change_profile_view


urlpatterns = [
    url(r'^profile/$',profile_view,name='profile'),
    url(r'^change_profile/$',change_profile_view,name='change_profile'),

]

oauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


class Ouser(AbstractUser):
    nickname = models.CharField('昵称', max_length=15, blank=True)
    avatar = ProcessedImageField(upload_to='avatar',
                                 default='avatar/default.jpg',
                                 verbose_name='头像',
                                 processors=[ResizeToFill(80, 80)], )

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

oauth/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Ouser

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Ouser
        fields = ['nickname','avatar']

oauth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

from .forms import ProfileForm
from django.contrib import messages
# Create your views here.

@login_required
def profile_view(request):
    return render(request,'oauth/profile.html')

@login_required
def change_profile_view(request):
    if request.method == 'POST':
        # 上传文件需要使用request.FILES
        form = ProfileForm(request.POST,request.FILES,instance=request.user)
        print(form)
        if form.is_valid():
            form.save()
            # 添加一条信息,重定向到个人信息页面
            messages.add_message(request,messages.SUCCESS,'个人信息更新成功！')
            return redirect('oauth:profile')
    else:
        form = ProfileForm(instance=request.user)
        return render(request,'oauth/change_profile.html',context={'form':form})

templates/oauth/change_profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title%}修改信息{% endblock%}

{% block content %}
<div class="container" id="oauth-account">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">修改资料</h3>
                </div>
                <div class="panel-body">
                    <form class="change_profile" method="post" enctype="multipart/form-data"
                          action="{% url 'oauth:change_profile'%}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-info btn-sm" type="submit">更新资料</button>
                    </form>
                </div>
                <div class="panel-footer text-center profile-more" id="social-login">
                    <div class="login-title">
                        <span>更多操作</span>
                    </div>
                    <div class="more-link">
                        <a class="btn btn-info btn-sm" href="{% url 'oauth:change_profile' %}">修改资料</a>
                        <a class="btn btn-info btn-sm" href="{% url 'account_change_password' %}">修改密码</a>
                        {% if user.is_staff %}
                        <a class="btn btn-info btn-sm" href="/admin/">后台管理</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/oauth/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load blog_tags %}

{% block head_title%}个人中心{% endblock%}

{% block content %}
<div class="container" id="oauth-account">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">个人中心</h3>
                </div>
                <div class="panel-body">
                    <ul class="list-group" id="profile-infos">
                        <li class="list-group-item" id="user-avatar">
                            <p class="text-center">
                                <img class="img-thumbnail" src="{{ user.avatar.url }}">
                            </p>
                        </li>
                        <li class="list-group-item" id="user-nickname">
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-4 col-xs-8 col-xs-offset-2">
                                    <span class="tab">昵&emsp;称：</span><span>{{ user.nickname }}</span>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item" id="user-username">
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-4 col-xs-8 col-xs-offset-2">
                                    <span class="tab">用户名：</span><span>{{ user.username }}</span>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item" id="user-email">
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-4 col-xs-8 col-xs-offset-2">
                                    <span class="tab">邮&emsp;箱：</span><span>{{ user.email|get_email_secret }}</span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="panel-footer text-center profile-more" id="social-login">
                    <div class="login-title">
                        <span>更多操作</span>
                    </div>
                    <div class="more-link">
                        <a class="btn btn-info btn-sm" href="{% url 'oauth:change_profile' %}">修改资料</a>
                        <a class="btn btn-info btn-sm" href="{% url 'account_change_password' %}">修改密码</a>
                        {% if user.is_staff %}
                        <a class="btn btn-info btn-sm" href="/admin/">后台管理</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}