blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import IndexView,TimelineView,DetailView,CategoryView,TagView,MySearchView,Aboutview,SilianView



urlpatterns = [
    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^timeline/$',TimelineView.as_view(),name='timeline'),
    url(r'^article/(?P<slug>[\w-]+)/$',DetailView.as_view(),name='detail'),
    url(r'^category/(?P<slug>[\w-]+)/$',CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<slug>[\w-]+)/$',TagView.as_view(),name='tag'),
    url(r'^search/$', MySearchView.as_view(), name='search_view'),
    url(r'^about/$',Aboutview,name='about'),
    url(r'^silian\.xml$',SilianView.as_view(content_type='application/xml'),name='silian'),
]

comment/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import comment_view,notifications,note_to_read,note_to_delete

urlpatterns = [
    url(r'^create/(?P<pk>\d+)/$',comment_view,name='comment_view'),
    url(r'^notifications/(?P<read>\w+)/$',notifications,name='notifications'),
    url(r'^notifications/(?P<read>\w+)/to_read/(?P<id>\d+)/$',note_to_read,name='note_to_read'),
    url(r'^notifications/(?P<read>\w+)/to_delete/(?P<id>\d+)/$',note_to_delete,name='note_to_delete'),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from blog.feeds import AllArticleRssFeed

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from django.views.generic import TemplateView

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comments/', include('comment.urls', namespace='comment')),  # comment
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^tools/',include('tools.urls',namespace='tools')), # tools
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

comment/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
import markdown
import emoji
# Create your models here.

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='评论人')
    create_date = models.DateTimeField('创建时间',auto_now_add=True)
    content = models.TextField('评论内容')
    belong = models.ForeignKey(Article,verbose_name='所属文章')
    parent = models.ForeignKey('self',verbose_name='父评论',related_name='child_comments',blank=True,null=True)
    rep_to = models.ForeignKey('self',verbose_name='回复',related_name='rep_comments',blank=True,null=True)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

    def __str__(self):
        return self.content[:20]

    def content_to_markdown(self):
        # 先转换成emoji然后转换成markdown,'escape':所有原始HTML将被转义并包含在文档中
        to_emoji_content = emoji.emojize(self.content, use_aliases=True)
        to_md = markdown.markdown(to_emoji_content, safe_mode='escape',extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        return to_md

class Notification(models.Model):
    create_p = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='提示创建者',related_name='create_p')
    get_p = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='提示接收者',related_name='get_p')
    to_article = models.ForeignKey(Article,verbose_name='所属文章',related_name='the_notify',default='')
    to_comment = models.ForeignKey(Comment,verbose_name='所属评论',related_name='the_comment',default='')
    create_date = models.DateTimeField('提示时间',auto_now_add=True)
    is_read = models.BooleanField('是否已读',default=False)

    class Meta:
        verbose_name = '提示信息'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return '{}@了{}'.format(self.create_p,self.get_p)

comment/views.py
from django.shortcuts import render,redirect

from blog.models import Article
from .models import Comment,Notification
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from . import handlers
from datetime import datetime
from django.shortcuts import get_object_or_404

user_model = settings.AUTH_USER_MODEL

@require_POST
def comment_view(request,pk):
    if request.is_ajax():
        data = request.POST
        new_user = request.user
        new_content = data['content']
        article_id = data['belong']
        the_article = Article.objects.get(id=article_id)
        parent_id = data['parent_id']
        rep_id = data['rep_id']
        if parent_id == 'base':
            new_comment = Comment(author=new_user,content=new_content,belong=the_article,parent=None,rep_to=None)
        else:
            new_parent = Comment.objects.get(id=parent_id)
            new_rep_id = rep_id.replace('rep-','')
            new_rep_to = Comment.objects.get(id=new_rep_id)
            new_comment = Comment(author=new_user, content=new_content, belong=the_article, parent=new_parent, rep_to=new_rep_to)
        new_comment.save()
        new_point = '#rep-' + str(new_comment.id)
        return JsonResponse({'msg':'评论提交成功！','new_point':new_point})
    return JsonResponse({'msg': '评论失败！'})

@login_required
def notifications(request,read):
    '''展示提示消息列表'''
    user = request.user
    now_date = datetime.now()
    return render(request,'comment/notification.html',context={'user':user,'read':read,'now_date':now_date})

@login_required
def note_to_read(request,read,id):
    '''将一个消息标记为已读'''
    user = request.user
    note = get_object_or_404(Notification,get_p=user,id=id)
    note.is_read = True
    note.save()
    now_date = datetime.now()
    return render(request, 'comment/notification.html', context={'user': user, 'read': read, 'now_date': now_date})

@login_required
def note_to_delete(request,read,id):
    '''将一个消息标记为已读'''
    user = request.user
    note = get_object_or_404(Notification,get_p=user,id=id)
    note.delete()
    now_date = datetime.now()
    return render(request, 'comment/notification.html', context={'user': user, 'read': read, 'now_date': now_date})

templates/comment/ajax_block.html
<script>
    $(document).ready(function(){
        <!--点击评论中回复按钮的时候定位到评论框，设置回复的信息-->
        $('.btn-reply').click(function(){
            $('#id_content').val('');
            $('#cancel-reply').removeClass('hidden');
            var rep_id = $(this).attr('id');
            var rep_name = $(this).attr('data-name');
            var par_id = $(this).attr('data-parent');
            $('.rep-to').removeClass('hidden').attr('id',rep_id).attr('data-par',par_id);
            $('#rep-user').text(rep_name);
            $('html,body').animate({scrollTop:$('#com-form').offset().top-90},100)
        });

        <!--评论提交后将页面刷新，并且定位到新的评论处-->
        if(sessionStorage.getItem('has_point')){
            var top = $(sessionStorage.getItem('new_point')).offset().top-100;
            $('body,html').animate({scrollTop:top}, 200);
            window.location.hash = sessionStorage.getItem('new_point');
            sessionStorage.removeItem('has_point');
        };

        <!--点击取消回复的时候，删除回复的的信息-->
        $('#cancel-reply').click(function(){
            $('.rep-to').addClass('hidden').removeAttr("id").removeAttr("data-par");
            $('#rep-user').text('');
            $('#cancel-reply').addClass('hidden');
            $('#id_content').val('');
        });

        $('.cannot-rep').click(function(){
            alert("登录后才能回复")
        });

        <!--点击提交评论，发送ajax-->
        $('.comment-post').click(function(){
            var has_id = $('.rep-to').attr('id');
            if (has_id){
                var rep_id = has_id
            }
            else{
                var rep_id = 'base'
            }
            var has_parent = $('.rep-to').attr('data-par');
            if (has_parent){
                var parent_id = has_parent
            }
            else{
                var parent_id = 'base'
            }
            var belong_id = {{ article.id }}
            var content = $('#id_content').val();
            if (content.length == 0){
                alert("评论内容不能为空！");
                return false;
            }
            $.ajaxSetup({
                data: {csrfmiddlewaretoken:'{{ csrf_token }}'}
                });
            $.ajax({
                type:'post',
                url:"{% url 'comment:comment_view' article.id %}",
                data:{'rep_id':rep_id,'content':content,'belong':belong_id,'parent_id':parent_id},
                dataType:'json',
                success:function(ret){
                    <!--alert(ret.msg)-->
                    $('#id_content').val('');
                    sessionStorage.setItem('has_point',true);
                    sessionStorage.setItem('new_point', ret.new_point);
                    window.location.reload();
                },
                error:function(ret){
                    alert(ret.msg);
                }
            });
        });
    });
</script>

templates/comment/comment_list.html
{% load static %}
{% load comment_tags %}
{% load blog_tags %}
{% load humanize %}

<div id="comment-main-block">
    {% if user.is_authenticated %}
    <div class="comment-form" id="com-form">
        <div class="hidden rep-to">
            <span>回复&nbsp;</span>
            @<span class="strong" id="rep-user"></span>
        </div>
        <div>
        <textarea class="form-control" id="id_content" name="content"
                  placeholder="评论支持markdown语法和emoji表情语法" rows="5" required></textarea>
        </div>
        <div class="comment-btns pull-right">
            <button class="btn btn-danger hidden " id="cancel-reply">取消回复</button>

            <button class="btn btn-info comment-post">提交评论</button>
        </div>
    </div>
    {% else %}
    <div class="well h4 text-center not-login">
        目前你尚未登录，请
        <a href="{% url 'account_login' %}?next={{ request.path }}">登录</a>
        后参与评论
    </div>
    {% endif %}
    <div class="comment-count" id="com-counter">
        <strong>{% get_comment_author_count article %}&nbsp;人参与&nbsp;|&nbsp;{% get_coms_count article %}&nbsp;条评论</strong>
    </div>
    {% get_comment_list article as comments %}
    <div class="comment-list">
        {% for each in comments %}
        <div class="parent-comments">
            <div class="media">
                <div class="media-left" id="com-avatar">
                    {% get_show_avatar each.author %}
                </div>
                <div class="media-body">
                    <div class="pull-right">
                        {% if user.is_authenticated %}
                        <button class="btn btn-default btn-xs btn-reply" id="rep-{{ each.id }}"
                                data-parent="{{ each.id }}"
                                data-name="{{ each.author }}">回复
                        </button>
                        {% else %}
                        <button class="btn btn-default btn-xs cannot-rep" title="请先登录！">回复</button>
                        {% endif %}
                    </div>
                    <h5 class="media-heading">
                        <strong>{{ each.author.username }}</strong>
                        {% if each.author.username == 'Hopetree' %}<span id="site-user">[博主]</span>{% endif %}
                    </h5>
                    <p class="small">{{ forloop.counter }}楼&nbsp;-&nbsp;{{ each.create_date|naturaltime }}</p>
                </div>
            </div>
            <div class="com-body">{{ each.content_to_markdown|safe }}</div>
        </div>
        {% get_child_comments each as childs %}
        {% if childs %}
        <ul>
            {% for each_child in childs %}
            <div class="child-comments">
                <div class="media">
                    <div class="media-left" id="com-avatar">
                        {% get_show_avatar each_child.author %}
                    </div>
                    <div class="media-body">
                        <div class="pull-right">
                            {% if user.is_authenticated %}
                            <button class="btn btn-default btn-xs btn-reply" id="rep-{{ each_child.id }}"
                                    data-parent="{{ each.id }}"
                                    data-name="{{ each_child.author }}">
                                回复
                            </button>
                            {% else %}
                            <button class="btn btn-default btn-xs cannot-rep" title="请先登录！">回复</button>
                            {% endif %}
                        </div>
                        <h5 class="media-heading">
                            <strong>{{ each_child.author.username }}</strong>
                            {% if each_child.author.username == 'Hopetree' %}<span id="site-user">[博主]</span>{% endif %}
                            <i class="glyphicon glyphicon-share-alt"></i>
                            @{{ each_child.rep_to.author.username }}
                        </h5>
                        <p class="small">{{ each_child.create_date|naturaltime }}</p>
                    </div>
                </div>
                <div class="com-body">{{ each_child.content_to_markdown|safe }}</div>
                <!--<p>我的父亲是：{{ each_child.parent }}</p>-->
            </div>
            {% endfor %}
            {% endif %}
        </ul>
        {% empty %}
        <div class="empty-com">
            <p>暂时没有评论，欢迎来尬聊！</p>
        </div>
        {% endfor %}
    </div>
</div>

templates/comment/notification.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}
{% load comment_tags %}

{% block head_title %}消息提示{% endblock %}

{% block css-file %}
<link href="{% static 'blog/mystyle/css/notification.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            {% get_notifications user read as notifications %}
            <ul class="cbp_tmtimeline">
                {% for each in notifications %}
                <li>
                    <time class="cbp_tmtime" datetime="{{ each.create_date }}">
                        <span>{{ each.create_date|date:"Y/m/d"}}</span>
                        <span>{{ each.create_date|date:"H:i"}}</span>
                    </time>
                    <div class="cbp_tmicon glyphicon glyphicon-envelope"></div>
                    <div class="cbp_tmlabel">
                        <h2>
                            <strong>{{ each.create_p }}</strong>&nbsp;在&nbsp;
                            <a href="{{ each.to_article.get_absolute_url }}#rep-{{ each.to_comment.id }}">
                                {{each.to_article.title }}</a>&nbsp;中@了你
                        </h2>
                        <p>{{ each.to_comment.content|truncatechars:130 }}</p>
                        {% if not each.is_read %}
                        <div class="to_read">
                            <a class="btn btn-success pull-right"
                               href="{% url 'comment:note_to_read' read=read id=each.id %}">标记为已读</a>
                        </div>
                        {% else %}
                        <div class="to_delete">
                            <a class="btn btn-danger pull-right"
                               href="{% url 'comment:note_to_delete' read=read id=each.id %}">删除</a>
                        </div>
                        {% endif %}
                    </div>
                </li>
                {% empty %}
                <li>
                    <time class="cbp_tmtime" datetime="{{ now_date }}">
                        <span>{{ now_date|date:"Y/m/d"}}</span>
                        <span>{{ now_date|date:"H:i"}}</span>
                    </time>
                    <div class="cbp_tmicon glyphicon glyphicon-envelope"></div>
                    <div class="cbp_tmlabel">
                        <h2>你暂时没有任何推送消息！</h2>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-3">
            <div class="panel panel-info" id="notes-main">
                <div class="panel-heading">
                    <h4><strong><i class="fa   fa-bell-o"></i>&nbsp;提示信息</strong></h4>
                </div>
                <div class="panel-body">
                    <ul class="list-group">
                        <a class="list-group-item {% if request.path == '/comments/notifications/all/' %}active{% endif %}"
                           href="{% url 'comment:notifications' 'all' %}">全部信息
                            <span class="badge">{% get_note_count user 'all' %}</span>
                        </a>
                        <a class="list-group-item {% if request.path == '/comments/notifications/read/' %}active{% endif %}"
                           href="{% url 'comment:notifications' 'read' %}">未读信息
                            <span class="badge">{% get_note_count user 'read' %}</span>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}