blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import IndexView,TimelineView,DetailView,CategoryView,TagView,MySearchView,Aboutview,SilianView



urlpatterns = [
    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^timeline/$',TimelineView.as_view(),name='timeline'),
    url(r'^article/(?P<slug>[\w-]+)/$',DetailView.as_view(),name='detail'),
    url(r'^category/(?P<slug>[\w-]+)/$',CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<slug>[\w-]+)/$',TagView.as_view(),name='tag'),
    url(r'^search/$', MySearchView.as_view(), name='search_view'),
    url(r'^about/$',Aboutview,name='about'),
    url(r'^silian\.xml$',SilianView.as_view(content_type='application/xml'),name='silian'),
]

comment/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import comment_view,notifications,note_to_read,note_to_delete

urlpatterns = [
    url(r'^create/(?P<pk>\d+)/$',comment_view,name='comment_view'),
    url(r'^notifications/(?P<read>\w+)/$',notifications,name='notifications'),
    url(r'^notifications/(?P<read>\w+)/to_read/(?P<id>\d+)/$',note_to_read,name='note_to_read'),
    url(r'^notifications/(?P<read>\w+)/to_delete/(?P<id>\d+)/$',note_to_delete,name='note_to_delete'),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from blog.feeds import AllArticleRssFeed

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from django.views.generic import TemplateView

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comments/', include('comment.urls', namespace='comment')),  # comment
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^tools/',include('tools.urls',namespace='tools')), # tools
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

oauth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import profile_view, change_profile_view


urlpatterns = [
    url(r'^profile/$',profile_view,name='profile'),
    url(r'^change_profile/$',change_profile_view,name='change_profile'),

]

tools/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import wordsearch,wordsearch_api

urlpatterns = [
    url(r'^wordsearch/$',wordsearch,name='wordsearch'),
    url(r'^wordserach_api/$',wordsearch_api,name='wordsearch_api'),
]

blog/models.py
from django.db import models
from django.conf import settings
import markdown
import emoji
from django.shortcuts import reverse
from django.utils.text import slugify


# Create your models here.

# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=15)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_article_list(self):
        '''返回当前标签下所有发表的文章列表'''
        return Article.objects.filter(tags=self, status='p')

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'slug': self.slug})

    # def save(self,*args,**kwargs):
    #     self.slug = slugify(self.slug)
    #     super(Tag,self).save()

# 文章分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=15)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

    def get_article_list(self):
        return Article.objects.filter(category=self, status='p')

    # def save(self,*args,**kwargs):
    #     self.slug = slugify(self.slug)
    #     super(Category,self).save()

# 文章
class Article(models.Model):
    IMG_LINK = settings.DEFAULT_IMG_LINL

    STATUS_CHOICE = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    status = models.CharField('文章状态', max_length=1, default='p', choices=STATUS_CHOICE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者')
    title = models.CharField(max_length=100, verbose_name='文章标题')
    summary = models.TextField('文章摘要', max_length=200, default='文章摘要是用来展示的，请务必填写...')
    body = models.TextField(verbose_name='文章内容')
    img_link = models.CharField('图片地址', default=IMG_LINK, max_length=255)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField('阅览量', default=0)
    slug = models.SlugField(unique=True)

    category = models.ForeignKey(Category, verbose_name='文章分类', blank=True, null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, verbose_name='标签')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id,status='p').order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id,status='p').order_by('id').first()

    # def save(self,*args,**kwargs):
    #     self.slug = slugify(self.slug)
    #     super(Article,self).save()

# 时间线
class Timeline(models.Model):
    COLOR_CHOICE = (
        ('primary', '基本-蓝色'),
        ('success', '成功-绿色'),
        ('info', '信息-天蓝色'),
        ('warning', '警告-橙色'),
        ('danger', '危险-红色')
    )
    SIDE_CHOICE = (
        ('L', '左边'),
        ('R', '右边'),
    )
    STAR_NUM = (
        (1,'1颗星'),
        (2,'2颗星'),
        (3,'3颗星'),
        (4,'4颗星'),
        (5,'5颗星'),
    )
    side = models.CharField('位置', max_length=1, choices=SIDE_CHOICE, default='L')
    star_num = models.IntegerField('星星个数',choices=STAR_NUM,default=3)
    icon = models.CharField('图标', max_length=50, default='glyphicon glyphicon-pencil')
    icon_color = models.CharField('图标颜色', max_length=20, choices=COLOR_CHOICE, default='info')
    title = models.CharField('标题', max_length=100)
    update_date = models.DateTimeField('更新时间')
    content = models.TextField('主要内容')

    class Meta:
        verbose_name = '时间线'
        verbose_name_plural = verbose_name
        ordering = ['update_date']

    def __str__(self):
        return self.title[:20]

    def title_to_emoji(self):
        return emoji.emojize(self.title,use_aliases=True)

    def content_to_markdown(self):
        # 先转换成emoji然后转换成markdown
        to_emoji_content = emoji.emojize(self.content,use_aliases=True)
        return markdown.markdown(to_emoji_content, extensions=[
            'markdown.extensions.extra',
        ])

# 幻灯片
class Carousel(models.Model):
    number = models.IntegerField('编号',help_text='编号决定图片播放的顺序')
    title = models.CharField('标题',max_length=20,blank=True,null=True,help_text='标题可以为空')
    content = models.CharField('描述',max_length=80)
    img_url = models.CharField('图片地址',max_length=200)
    url = models.CharField('跳转链接',max_length=200,default='#',help_text='图片跳转的超链接，默认#表示不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        ordering = ['number','id']

    def __str__(self):
        return self.title


# 死链
class Silian(models.Model):
    badurl = models.CharField('死链地址',max_length=200,help_text='地址必须带http')
    remark = models.CharField('死链说明',max_length=50,blank=True,null=True)
    add_date = models.DateTimeField('提交日期',auto_now_add=True)

    class Meta:
        verbose_name = '死链'
        verbose_name_plural = verbose_name
        ordering = ['-add_date']

    def __str__(self):
        return self.badurl

blog/views.py
from .models import Article, Tag, Category, Timeline, Silian
from django.views import generic
# Create your views here.
import markdown
from markdown.extensions.toc import TocExtension  # 锚点的拓展
from django.utils.text import slugify  # 这个目测是URL支持中文的拓展
from haystack.generic_views import SearchView  # 导入搜索视图
from django.shortcuts import get_object_or_404, render
import time
from haystack.query import SearchQuerySet

def Aboutview(request):
    return render(request,'blog/about.html',context={})

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'article_list'
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.filter(status='p')


class TimelineView(generic.ListView):
    template_name = 'blog/timeline.html'
    context_object_name = 'timeline_list'

    def get_queryset(self):
        return Timeline.objects.all()


class DetailView(generic.DetailView):
    model = Article
    slug_url_kwarg = 'slug'
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get_queryset(self):
        queryset = super(DetailView, self).get_queryset()
        return queryset.filter(status='p')

    def get_object(self):
        obj = super(DetailView, self).get_object()
        # 设置浏览量增加时间判断,同一篇文章两次浏览超过2小时才重新统计阅览量,作者浏览忽略
        u = self.request.user
        ses = self.request.session
        the_key = 'is_read_{}'.format(obj.id)
        is_read_time = ses.get(the_key)
        if not is_read_time:
            if u != obj.author:
                obj.update_views()
                ses[the_key] = time.time()
        else:
            now_time = time.time()
            t = now_time - is_read_time
            if t > 7200 and u != obj.author:
                obj.update_views()
                ses[the_key] = time.time()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        obj.body = md.convert(obj.body)
        obj.toc = md.toc
        return obj

class CategoryView(generic.ListView):
    model = Article
    template_name = 'blog/category_and_tag.html'
    context_object_name = 'article_list'
    paginate_by = 10

    def get_queryset(self, **kwargs):
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return super(CategoryView, self).get_queryset().filter(category=cate, status='p')

    def get_context_data(self, **kwargs):
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        context_data = super(CategoryView, self).get_context_data()
        context_data['search_tag'] = '分类'
        context_data['search_name'] = cate
        return context_data


class TagView(generic.ListView):
    model = Article
    template_name = 'blog/category_and_tag.html'
    context_object_name = 'article_list'
    paginate_by = 10

    def get_queryset(self, **kwargs):
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        return super(TagView, self).get_queryset().filter(tags=tag, status='p')

    def get_context_data(self, **kwargs):
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        context_data = super(TagView, self).get_context_data()
        context_data['search_tag'] = '标签'
        context_data['search_name'] = tag
        return context_data


# 重写搜索视图，可以增加一些额外的参数，且可以重新定义名称
class MySearchView(SearchView):
    context_object_name = 'search_list'
    paginate_by = 10
    queryset = SearchQuerySet().filter(status='p').order_by('-views')

    def get_queryset(self):
        queryset = super(MySearchView, self).get_queryset()
        # 这个过滤有问题，并没有把status='d'的过滤掉，这是个bug目前不得解
        return queryset.filter(status='p')

class SilianView(generic.ListView):
    model = Silian
    template_name = 'silian.xml'
    context_object_name = 'badurls'

templates/blog/tags/article-summary.html
{% load blog_tags %}
{% load humanize %}
{% load comment_tags %}
<div class="media article-item">
    <div class="media-left media-middle hidden-xs">
        <a href="{{ article.get_absolute_url }}" target="_blank">
            <img class="media-object img-rounded" src="{{ article.img_link }}" alt="img_{{ article.id }}">
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading" ><a class="article-title" href="{{ article.get_absolute_url }}"><strong>{{ article.title }}</strong></a></h4>
        <ul class="list-inline small article-infos info-top">
            <li class="article-author"><i class="fa fa-user-circle"></i> {{ article.author }}</li>
            <li class="article-create-date">
                <i class="fa fa-calendar-times-o"></i> {{ article.create_date|naturaltime}}
            </li>
        </ul>
        <p>{{ article.summary|truncatechars:130 }}</p>
        <ul class=" list-inline small article-infos info-bottom">
            <li>
                <a class="article-category" href="{{ article.category.get_absolute_url }}" title="查看当前分类下更多文章">
                    <i class="fa fa-th-list"></i> {{ article.category }}</a>
            </li>
            <li class="article-views"><i class="fa fa-eye"></i> {{ article.views }}</li>
            <li>
                <a class="article-comments" href="{{ article.get_absolute_url }}#comment-main-block" title="查看文章评论">
                    <i class="fa fa-commenting"></i> {% get_coms_count article %}</a>
            </li>
        </ul>
    </div>
</div>

templates/blog/tags/base-footer.html
<footer>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="text-center">
                    <p>Copyright&nbsp;©&nbsp;2017&nbsp;<a href="https://github.com/Hopetree" target="_blank" title="前往博主的Github">Hopetree</a>&nbsp;|&nbsp;Powered&nbsp;by&nbsp;Django</p>
                    <p>
                        <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备17114114号</a>
                        <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1271548398'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s13.cnzz.com/z_stat.php%3Fid%3D1271548398%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
                    </p>
                </div>
            </div>
        </div>
        </div>
    </nav>
</footer>

templates/blog/tags/base-right.html
{% load static %}
{% load blog_tags %}

<!--个人中心开始-->
<div class="panel panel-info" id="focus">
    <div class="panel-heading">
        <h4><strong><i class="fa fa-home fa-lg"></i> 个人空间</strong></h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-4">
                <a href="https://github.com/Hopetree" target="_blank">
                    <img src="{% static 'blog/img/github.png' %}" class="img-responsive center-block">
                </a>
                <p class="text-center">Github</p>
            </div>
            <div class="col-xs-4">
                <a href="{% url 'blog:timeline' %}" target="_blank">
                    <img src="{% static 'blog/img/blog.png' %}" class="img-responsive center-block">
                </a>
                <p class="text-center">Timeline</p>
            </div>
            <div class="col-xs-4">
                <a href="{% url 'rss' %}" target="_blank">
                    <img src="{% static 'blog/img/rss.png' %}" class="img-responsive center-block">
                </a>
                <p class="text-center">RSS订阅</p>
            </div>
        </div>
    </div>
</div>
<!--个人中心结束-->

<!-- 文章分类开始 -->
<div class="panel panel-info" id="category-box">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <h4><strong><i class="glyphicon glyphicon-list"></i> 文章分类</strong></h4>
    </div>
    <!-- List group -->
    <ul class="list-group">
        {% get_category_list as categories %}
        {% for cate in categories %}
        <li class="list-group-item">
            <a href="{{ cate.get_absolute_url }}" title="点击查看【{{ cate.name }}】分类下所有文章"><strong>{{ cate.name }}</strong></a>
            <span class="pull-right text-center" title="当前分类下有{{ cate.get_article_list.count }}篇文章发表">{{ cate.get_article_list.count }}</span>
        </li>
        {% endfor %}
    </ul>
</div>
<!-- 文章分类结束 -->

<!--标签云-->
<div class="panel panel-info" id="tag-cloud">
    <div class="panel-heading">
        <h4><strong><i class="fa fa-tags"></i> 标签云</strong></h4>
    </div>
    <div class="panel-body">
        <div class="tag-cloud">
            {% get_tag_list as tag_list %}
            {% for tag in tag_list %}
            <a href="{{ tag.get_absolute_url }}" class="tags" id="tag-{{ forloop.counter }}"
               title="【{{ tag.name }}】标签下有{{ tag.get_article_list.count }}篇文章">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
</div>

templates/blog/tags/carousel.html
{% load static blog_tags %}
<!--这个效果的图片不会压缩，而是等比例缩放，当宽度不够的时候就补充空白，所以最好把图片先裁剪好-->
<!--图片大小可以不统一，但是比例需要统一，推荐比例16:9-->
{% get_carousel_list as carousels %}
<div id="my-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        {% for each in carousels %}
        {% if forloop.counter0 == 0 %}
        <li data-target="#my-carousel" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
        {% else %}
        <li data-target="#my-carousel" data-slide-to="{{ forloop.counter0 }}"></li>
        {% endif %}
        {% endfor %}
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        {% for each in carousels %}
        {% if forloop.counter0 == 0 %}
        <div class="item active">{% else %}
            <div class="item">{% endif %}
                <a href="{{ each.url }}">
                    <img src="{{ each.img_url }}" alt="{{ each.content }}">
                </a>
                <div class="carousel-caption">
                    {% if each.title %}<h3>{{ each.title }}</h3>{% endif %}
                    <p>{{ each.content }}</p>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Controls -->
        <a class="left carousel-control" id="move-btn" href="#my-carousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" id="move-btn" href="#my-carousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

templates/blog/tags/navbar.html
{% load static %}
{% load blog_tags comment_tags %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header hidden-sm">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="{% static 'blog/img/logo.png'%}">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right" id="bs-navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">主页</a></li>
                <li><a href="#">杂文</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">我的工具 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'tools:wordsearch' %}" title="通过关键词搜索得到电商平台展示的商品数及其他信息">电商平台搜索</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'blog:about' %}">关于</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" id="searchform"
                  action="{% url 'blog:search_view'%}">
                <div class="input-group">
                    <input type="search" name="q" class="form-control" placeholder="搜索" required=True>
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </span>
                </div><!-- /input-group -->
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" id="user-avatar" data-toggle="dropdown"
                       role="button" aria-haspopup="true" aria-expanded="false" title="{{ user|get_show_name }}，欢迎你！">
                        {% get_show_avatar user %} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" id="is_log">
                        <li><a href="{% url 'oauth:profile' %}"><i class="glyphicon glyphicon-user"></i>个人中心</a></li>
                        <li><a href="{% url 'comment:notifications' 'all' %}"><i class="glyphicon glyphicon-envelope"></i>消息
                            {% get_note_count user 'read' as note_num %}
                            {% if note_num %}
                            <span class="badge">{% get_note_count user 'read' %}</span></a>
                            {% endif %}
                        </li>
                        <li><a href="{% url 'account_logout' %}"><i class="glyphicon glyphicon-log-out"></i>退出</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{% url 'account_login' %}?next={{ request.path }}">登录</a></li>
                <li class="active"><a href="{% url 'account_signup' %}?next={{ request.path }}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

templates/blog/tags/paging.html
<!--分页模板，标签函数中不需要传递参数，直接调用上级参数即可-->
<div class="well text-center cut-page">
    <ul class="list-inline">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% else %}
        <li class="no-page" title="当前页已经是首页">上一页</li>
        {% endif %}
        <li>第 {{ page_obj.number }} / {{ paginator.num_pages }} 页</li>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% else %}
        <li class="no-page" title="当前页已经是末页">下一页</li>
        {% endif %}
    </ul>
</div>

templates/blog/tags/user-avatar.html
{% if user.socialaccount_set.exists %}
{% if user.avatar.url != '/media/avatar/default.jpg' %}
<img src="{{ user.avatar.url }}" alt="本地头像">
{% else %}
<img src="{{ user.socialaccount_set.all.0.get_avatar_url}}" alt="网络头像">
{% endif %}
{% else %}
<img src="{{ user.avatar.url }}" alt="本地头像">
{% endif %}